#!perl

use alienfile;


plugin 'PkgConfig' => (
  pkg_name => 'tidy',
);

share {

    plugin 'Build::CMake';

    start_url 'https://github.com/htacg/tidy-html5/archive/5.6.0.tar.gz';

    # the first one which succeeds will be used
    download [ 'wget %{.meta.start_url}' ];
    download [ 'curl -o %{.meta.start_url}' ];

    extract [ 'tar xf %{.install.download}' ];

    build [
        [ '%{cmake}', -G => '%{cmake_generator}', '-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true', '-DCMAKE_INSTALL_PREFIX:PATH=%{.install.prefix}', '.' ],
        '%{make}',
        '%{make} install',
    ];

}
